// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-gIASke2bULCYi3Zq7DE2w_5EB-su7U',
    appId: '1:635666592641:web:dca7ec7175bd8c263eae80',
    messagingSenderId: '635666592641',
    projectId: 'synchrom-6ec50',
    authDomain: 'synchrom-6ec50.firebaseapp.com',
    storageBucket: 'synchrom-6ec50.firebasestorage.app',
    measurementId: 'G-5F4C9E9KKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3eFLywrquWtYkV01_A9Lo9WNP8Sdw10',
    appId: '1:635666592641:android:eb92c1bae49864563eae80',
    messagingSenderId: '635666592641',
    projectId: 'synchrom-6ec50',
    storageBucket: 'synchrom-6ec50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuan-OxtCk2pS58RzmSjWSOWbqXjEl2lI',
    appId: '1:635666592641:ios:85dab9047209372a3eae80',
    messagingSenderId: '635666592641',
    projectId: 'synchrom-6ec50',
    storageBucket: 'synchrom-6ec50.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuan-OxtCk2pS58RzmSjWSOWbqXjEl2lI',
    appId: '1:635666592641:ios:85dab9047209372a3eae80',
    messagingSenderId: '635666592641',
    projectId: 'synchrom-6ec50',
    storageBucket: 'synchrom-6ec50.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-gIASke2bULCYi3Zq7DE2w_5EB-su7U',
    appId: '1:635666592641:web:6d028ee0822b13653eae80',
    messagingSenderId: '635666592641',
    projectId: 'synchrom-6ec50',
    authDomain: 'synchrom-6ec50.firebaseapp.com',
    storageBucket: 'synchrom-6ec50.firebasestorage.app',
    measurementId: 'G-RKQCYTR40F',
  );
}
